### ISSUE TITLE
error: no rules expected the token `as`

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/rust-docker-isolation-provider#13]
```rust
error: no rules expected the token `as`
   --> _0/template/src/lib.rs:205:24
    |
181 | macro_rules! __main_attr {
    | ------------------------ when calling this macro
...
205 |         use serde_json as json;
    |                        ^^ no rules expected this token in macro call
    |
note: while trying to match `;`
   --> _0/template/src/lib.rs:185:21
    |
185 |     $(use $path:path;)*
    |                     ^
```
### Handler Code
```rust
use serde_json as json;

// Hello world handler in general form
async |Ctx { _data, _deep, .. }: Ctx<json::Value>| {
    2 + 2
}
```

**Comment by uselessgoddess** [comment]
This is due to the implementation of an internal macro. I'm already in the process of fixing

**Comment by FreePhoenix888** [comment]
> This is due to the implementation of an internal macro. I'm already in the process of fixing

Thank you!

**Comment by uselessgoddess** [comment]
For now, for simplicity, it's not possible to write any code before the handler's future, so I just explicitly allowed `use .. as ..` in this commit: https://github.com/deep-foundation/rust-docker-isolation-provider/commit/46ebd2e959aa9f585792b82714ef84307563eaa5
